spring.application.name=ResumeBuilder
spring.data.mongodb.uri=mongodb://localhost:27017/ResumeBuilder
spring.data.mongodb.auto-index-creation=true

#email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9e59cf001@smtp-brevo.com
spring.mail.password=bskyvm5IwJNnUY9

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=khushiarya409@gmail.com

#App configuration
app.base.url=http://localhost:8080

#cloudnary info
cloudinary.cloud-name=dq6a3ykp8
cloudinary.api-key=553566597146879
cloudinary.api-secret=gOi2NCR3nzbMuui_8JB4DZb7LuM

# JWT configuration
jwt.secret=MySuperSecretJWTKey_ChangeThis_AtLeast32CharactersLong
jwt.expiration=86400000

# Rozarpay info
rozorpay.key.id=rzp_test_RvuWAv8oNuCJJU
rozorpay.key.secrete=sjyUZtYDKZFV5jHS40olU7av