name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST "https://gitlab.com/api/v4/projects/81899170/trigger/pipeline" \
          --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
          --form ref=main
